name: Publish Package

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installing CI package manager
        run: npm i -g @antfu/ni

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: nci

      - run: nr build --if-present

      - run: nr publish